/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bbutvmfokwcbzeiacejj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJidXR2bWZva3djYnplaWFjZWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2Nzc3MDgsImV4cCI6MjA4NTI1MzcwOH0.14ynv58I2hQKbnvkK-d6lOosbro_vUwbgJeZETFAKXY"
