/// <reference lib="webworker" />

import { precacheAndRoute } from 'workbox-precaching';

const sw = (self as unknown) as ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute((self as any).__WB_MANIFEST);

// 1. Force new versions immediately
sw.addEventListener("install", () => {
    sw.skipWaiting();
});

// 2. Clear old caches and take control immediately
sw.addEventListener("activate", (event) => {
    event.waitUntil(
        caches.keys().then((keys) =>
            Promise.all(
                keys.map((key) => caches.delete(key))
            )
        ).then(() => sw.clients.claim())
    );
});

// 3. Smart Caching Strategy
sw.addEventListener("fetch", (event) => {
    const url = new URL(event.request.url);

    // API / Dynamic Data -> NETWORK-FIRST
    // We never want to serve stale payment or student data if the network is available
    if (url.href.includes("supabase.co") || url.pathname.includes("/api/")) {
        event.respondWith(
            fetch(event.request)
                .then((res) => {
                    const clone = res.clone();
                    caches.open("api-cache").then((cache) => {
                        cache.put(event.request, clone);
                    });
                    return res;
                })
                .catch(() => caches.match(event.request))
        );
        return;
    }

    // Static Assets -> CACHE-FIRST (Handled by precacheAndRoute for most things)
});

// Allow the web app to trigger skipWaiting manually if needed
sw.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        sw.skipWaiting();
    }
});

// Handle push notifications
sw.addEventListener('push', (event: any) => {
    if (!event.data) return;

    try {
        const data = event.data.json();
        const { title, body, icon, data: meta } = data;

        const options = {
            body: body || 'You have a new payment reminder.',
            icon: icon || '/pwa-192x192.png',
            badge: '/favicon.png',
            vibrate: [100, 50, 100],
            data: meta || { url: '/' },
            actions: [
                { action: 'pay', title: 'Pay Now' },
                { action: 'close', title: 'Dismiss' }
            ]
        };

        event.waitUntil(
            sw.registration.showNotification(title || 'Master-Fees Reminder', options)
        );
    } catch (err) {
        console.error('Error handling push event:', err);
    }
});

// Handle notification clicks
sw.addEventListener('notificationclick', (event: any) => {
    event.notification.close();

    if (event.action === 'close') return;

    const urlToOpen = event.notification.data?.url || '/';

    event.waitUntil(
        sw.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients: readonly any[]) => {
            // Check if there is already a window open and focus it
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus();
                }
            }
            // If not, open a new window
            if (sw.clients.openWindow) {
                return sw.clients.openWindow(urlToOpen);
            }
        })
    );
});
